### PR TITLE
Removing 'If' check from 'TestBoundedBufferFindDeadlockConfiguration'.

### PR DESCRIPTION
**Pull request by ShreyTiwari**
Removing the 'If' check from the 'TestBoundedBufferFindDeadlockConfiguration' test case to increase readability.

### CODE REVIEW

**Comment by lovettchris** [comment]
Can you also move Common\version.props to match the latest Coyote version 1.2.8 ?

**Review by lovettchris — COMMENTED** [review]
Could also do this to further simplify:

```csharp
            int x = 0;
            int index = 0;
            foreach (var g in Enumerable.Range(0, totalIterations).GroupBy(x => index++ % writers))
            {
                int w = g.Count();
                x += w;
                tasks.Add(Task.Run(() => Writer(buffer, w)));
            }
```

**Review by lovettchris — COMMENTED** [review]
isn't this also simpler, so you don't need the Convert.ToInt16 ?
```csharp
int w = writerIterations + ((i == writers - 1) ? remainder : 0);
```

**Comment by ShreyTiwari** [comment]
> isn't this also simpler, so you don't need the Convert.ToInt16 ?
> 
> ```cs
> int w = writerIterations + ((i == writers - 1) ? remainder : 0);
> ```

Sure, this seems like a better approach. I have updated the PR.

**Review by lovettchris — APPROVED** [review]

**Pull request merged**
